<a href="https://colab.research.google.com/github/mustafajnedian/python-ml-nb/blob/main/ML_concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import nltk

In [4]:
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [20]:
from nltk.tokenize import word_tokenize

text = "Tokenization is the process of splitting text into smaller units, called tokens. These tokens can be words, subwords, or characters."
tokens = word_tokenize(text)
print(tokens)

['Tokenization', 'is', 'the', 'process', 'of', 'splitting', 'text', 'into', 'smaller', 'units', ',', 'called', 'tokens', '.', 'These', 'tokens', 'can', 'be', 'words', ',', 'subwords', ',', 'or', 'characters', '.']


In [21]:
print('Tokenization is the process of splitting text into smaller units, called tokens. These tokens can be words, subwords, or characters.')

Tokenization is the process of splitting text into smaller units, called tokens. These tokens can be words, subwords, or characters.


In [22]:
print('It helps break down text into meaningful parts for further processing.')

It helps break down text into meaningful parts for further processing.


In [23]:
print('Encoding converts categorical text data (tokens) into numerical form.')

Encoding converts categorical text data (tokens) into numerical form.


In [24]:
from sklearn.preprocessing import LabelEncoder

labels = ['Tokenization', 'is', 'the', 'process', 'of', 'splitting', 'text', 'into', 'smaller', 'units', ',', 'called', 'tokens', '.', 'These', 'tokens', 'can', 'be', 'words', ',', 'subwords', ',', 'or', 'characters', '.']
encoder = LabelEncoder()
encoded_labels = encoder.fit_transform(labels)
print(encoded_labels)


[ 3  9 17 12 10 14 16  8 13 19  0  5 18  1  2 18  6  4 20  0 15  0 11  7
  1]


> ML models only understand numbers, so we map categories.

In [25]:
print(' ML models only understand numbers, so we map categories.')

 ML models only understand numbers, so we map categories.


> **3. Vectorizing Definition:** Vectorization converts text data into numerical vectors for ML models. Common methods include CountVectorizer and TF-IDF.

**Example 1 (Count Vectorization - Bag of Words)**:


In [29]:
from sklearn.feature_extraction.text import CountVectorizer

texts = ["Machine learning is amazing", "Deep learning is powerful", "Basketball learning is very amazing"]
vectorizer = CountVectorizer()
vectorized_texts = vectorizer.fit_transform(texts)

print(vectorizer.get_feature_names_out())
print(vectorized_texts.toarray())


['amazing' 'basketball' 'deep' 'is' 'learning' 'machine' 'powerful' 'very']
[[1 0 0 1 1 1 0 0]
 [0 0 1 1 1 0 1 0]
 [1 1 0 1 1 0 0 1]]


**Example 2 (TF-IDF Vectorization)**

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

texts = ["Machine learning is amazing", "Deep learning is powerful", "Basketball learning is very amazing"]
vectorizer = TfidfVectorizer()
vectorized_texts = vectorizer.fit_transform(texts)

print(vectorizer.get_feature_names_out())
print(vectorized_texts.toarray())


['amazing' 'basketball' 'deep' 'is' 'learning' 'machine' 'powerful' 'very']
[[0.50410689 0.         0.         0.39148397 0.39148397 0.66283998
  0.         0.        ]
 [0.         0.         0.6088451  0.35959372 0.35959372 0.
  0.6088451  0.        ]
 [0.42018292 0.55249005 0.         0.32630952 0.32630952 0.
  0.         0.55249005]]


> **Conclusion**
- Use Tokenization to break text into pieces.
- Use Encoding to convert categorical text labels to numbers.
- Use Embeddings to learn meaningful vector representations.
- Use Vectorization to transform text into numerical input for ML models

> **4. Embedding Definition:** Embeddings map words/tokens into dense numerical vectors in a continuous space, capturing relationships between words.
> Example (Using Word2Vec for word embeddings)

In [26]:
from gensim.models import Word2Vec

sentences = [["machine", "learning", "is", "fun"], ["deep", "learning", "is", "powerful"]]
model = Word2Vec(sentences, vector_size=5, min_count=1, window=3)

vector = model.wv["learning"]
print(vector)  # Word embedding for "learning"


[-0.14233617  0.12917745  0.17945977 -0.10030856 -0.07526743]


In [27]:
from gensim.models import Word2Vec

sentences = [["machine", "learning", "is", "fun"], ["deep", "learning", "is", "powerful"]]
model = Word2Vec(sentences, vector_size=10, min_count=1, window=6)

vector = model.wv["machine"]
print(vector)  # Word embedding for "machine"


[-0.08157917  0.04495798 -0.04137076  0.00824536  0.08498619 -0.04462177
  0.045175   -0.0678696  -0.03548489  0.09398508]


Embeddings capture semantic relationships between words (e.g. Word2Vec), while vectorizing methods like bag-of-words and TF-IDF focus on word frequencies and occurrences.


In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

texts = ["I love machine learning", "Deep learning is powerful"]
vectorizer = TfidfVectorizer()
vectorized_texts = vectorizer.fit_transform(texts)

print('Vectorizing with TF-IDF (Sparse Representation)\n\n')
print(vectorizer.get_feature_names_out())  # Words in vocabulary
print(vectorized_texts.toarray())  # TF-IDF matrix
print('\n\nA sparse matrix where each word is a feature.')

Vectorizing with TF-IDF (Sparse Representation)


['deep' 'is' 'learning' 'love' 'machine' 'powerful']
[[0.         0.         0.44943642 0.6316672  0.6316672  0.        ]
 [0.53404633 0.53404633 0.37997836 0.         0.         0.53404633]]


A sparse matrix where each word is a feature.


In [37]:
from gensim.models import Word2Vec

sentences = [["I", "love", "machine", "learning"], ["Deep", "learning", "is", "powerful"]]
model = Word2Vec(sentences, vector_size=5, min_count=1)

vector = model.wv["learning"]
print(vector)  # Dense word embedding for "learning"


[-0.01072454  0.00472863  0.10206699  0.18018547 -0.186059  ]


Traditional ML → Use Vectorization

Deep Learning → Use Embeddings

📌 Scenario: Spam Detection in Messages
We will classify text messages as spam (1) or ham (0).

Approach 1: Using TF-IDF + Logistic Regression (Vectorization for ML)

In [71]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


In [72]:
data = {
    "text": [
        "Win a free iPhone now!",
        "Hey, let's meet for lunch.",
        "Congratulations, you won a lottery!",
        "Call me when you're free.",
        "Get a free gift card by clicking this link."
    ],
    "label": [1, 0, 1, 0, 1]  # 1 = Spam, 0 = Ham
}

df = pd.DataFrame(data)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(df["text"], df["label"], test_size=0.2, random_state=42)


In [73]:
print(df)

                                          text  label
0                       Win a free iPhone now!      1
1                   Hey, let's meet for lunch.      0
2          Congratulations, you won a lottery!      1
3                    Call me when you're free.      0
4  Get a free gift card by clicking this link.      1


In [74]:
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)


In [75]:
model = LogisticRegression()
model.fit(X_train_tfidf, y_train)


LogisticRegression()

In [76]:
y_pred = model.predict(X_test_tfidf)
print("Accuracy:", accuracy_score(y_test, y_pred))


Accuracy: 0.0


In [78]:
# Define new test samples
new_texts = ["Get a free iPhone now!", "Let's grab coffee tomorrow.", "Let's work on the next sprint in our Agile Project"]

# Transform using the same TF-IDF vectorizer
new_texts_tfidf = vectorizer.transform(new_texts)

# Predict
predictions = model.predict(new_texts_tfidf)

# Show results
for text, label in zip(new_texts, predictions):
    print(f"Text: {text} -> Predicted: {'Spam' if label == 1 else 'Ham'}")


Text: Get a free iPhone now! -> Predicted: Spam
Text: Let's grab coffee tomorrow. -> Predicted: Spam
Text: Let's work on the next sprint in our Agile Project -> Predicted: Spam


🚀 Approach 2: Using Word Embeddings (Word2Vec) + LSTM (Deep Learning)

In [79]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense


In [80]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_test_seq = tokenizer.texts_to_sequences(X_test)

# Pad sequences to ensure uniform input size
X_train_pad = pad_sequences(X_train_seq, maxlen=5, padding="post")
X_test_pad = pad_sequences(X_test_seq, maxlen=5, padding="post")


In [81]:
vocab_size = len(tokenizer.word_index) + 1  # Vocabulary size
embedding_dim = 8  # Small embedding size

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=5),
    LSTM(10, return_sequences=False),
    Dense(1, activation="sigmoid")
])

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [82]:
model.fit(X_train_pad, np.array(y_train), epochs=10, batch_size=2)


Epoch 1/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 2s 27ms/step - accuracy: 0.0000e+00 - loss: 0.7009
Epoch 2/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.0000e+00 - loss: 0.6966
Epoch 3/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8333 - loss: 0.6933
Epoch 4/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6921
Epoch 5/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6667 - loss: 0.6896
Epoch 6/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - accuracy: 0.6667 - loss: 0.6871
Epoch 7/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6667 - loss: 0.6846
Epoch 8/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - accuracy: 0.6667 - loss: 0.6821
Epoch 9/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6667 - loss: 0.6795
Epoch 10/10
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.6667 - loss: 0.6771


In [83]:
y_pred = (model.predict(X_test_pad) > 0.5).astype("int32")
print("Accuracy:", accuracy_score(y_test, y_pred))


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 201ms/step
Accuracy: 0.0


In [84]:
# Define new test samples
new_texts = ["Get a free iPhone now!", "Let's grab coffee tomorrow.", "Let's work on the next sprint in our Agile Project"]

# Convert to sequences
new_texts_seq = tokenizer.texts_to_sequences(new_texts)

# Pad sequences
new_texts_pad = pad_sequences(new_texts_seq, maxlen=5, padding="post")

# Predict using LSTM model
predictions = (model.predict(new_texts_pad) > 0.5).astype("int32")

# Show results
for text, label in zip(new_texts, predictions):
    print(f"Text: {text} -> Predicted: {'Spam' if label == 1 else 'Ham'}")


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 346ms/step
Text: Get a free iPhone now! -> Predicted: Spam
Text: Let's grab coffee tomorrow. -> Predicted: Spam
Text: Let's work on the next sprint in our Agile Project -> Predicted: Spam
